#!/bin/env bash

name="$1"; shift
year=$1; shift
title=$1; shift
location=$1; shift

if [[ $name == '' || $year == '' ]]; then
  echo "rip_movie <name> <year> [Owned | Rentals] [title number, default: '0']"
  exit 1
fi


[[ $title ]] || title=0
destination=/media
minlength=3600
[[ $year == 'tv' ]] && season_number=$title && title=all && minlength=1800

mkdir -p $destination/discinfo
makemkvcon --messages="$destination/discinfo/$name ($year).txt" --robot info disc:0
makemkvcon --minlength=$minlength mkv disc:0 $title $destination

if [[ $? == 0 ]]; then
#  if [[ $season_number ]]; then
    # check existing episodes in season folder and increment to next one
    # or start from '01'

#  else
    filename="$name (${year}).mkv"
    mv *.mkv "$filename"
    move_to_plex "$filename" "$location"
#  fi
  eject
else
  echo MAKEMKV FAILED: Problem ripping disc
  echo Removing partially created files...
  rm $destination/*.mkv
fi

